[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.coverage.run]
source = ["adcp"]
omit = [
    "*/__init__.py",
    "*/tests/*"
]


[tool.black]
verbose = 1
exclude = '''
(
    setup.py
  | adcp-env
)
'''