[build-system]
requires = ["setuptools", "wheel"]

[tool.coverage.run]
source = ["adcp"]
omit = [
    "*/__init__.py",
    "*/tests/*"
]

[tool.black]
line-length = 79
experimental-string-processing = 1
verbose = 1
exclude = '''
(
  adcp-env
)
'''